name: Update README.md

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  markscribe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          template: "templates/README.md.template"
          writeTo: "README-test.md"

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update generated README.md"
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
